app_mailing/urls.py
from django.urls import path

from app_mailing.apps import AppMailingConfig

from . import views

app_name = AppMailingConfig.name

urlpatterns = [
    path("recipients/", views.RecipientListView.as_view(), name="recipient_list_page"),
    path("recipients/add/", views.RecipientCreateView.as_view(), name="recipient_add_page"),
    path("recipients/<int:pk>/update/", views.RecipientUpdateView.as_view(), name="recipient_update_page"),
    path("recipients/<int:pk>/delete/", views.RecipientDeleteView.as_view(), name="recipient_delete_page"),
    path("messages/", views.MessageListView.as_view(), name="message_list_page"),
    path("messages/add/", views.MessageCreateView.as_view(), name="message_add_page"),
    path("messages/<int:pk>/update/", views.MessageUpdateView.as_view(), name="message_update_page"),
    path("messages/<int:pk>/delete/", views.MessageDeleteView.as_view(), name="message_delete_page"),
    path("mailings/", views.MailingListView.as_view(), name="mailing_list_page"),
    path("mailings/add/", views.MailingCreateView.as_view(), name="mailing_add_page"),
    path("mailings/<int:pk>/update/", views.MailingUpdateView.as_view(), name="mailing_update_page"),
    path("mailings/<int:pk>/delete/", views.MailingDeleteView.as_view(), name="mailing_delete_page"),
    path("start-mailing/<int:pk>/", views.SendMailingView.as_view(), name="start_mailing_page"),
    path("stop-mailing/<int:pk>/", views.StopMailingView.as_view(), name="stop_mailing_page"),
    path("mailings/<int:pk>/schedule/", views.ScheduleMailingModalView.as_view(), name="schedule_mailing_page"),
    path("main/", views.MainPageView.as_view(), name="main_page"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # namespace="app_mailing" это заданное пространство имен в "app_mailing/urls.py" с помощью "CatalogConfig.name"
    path("mailing/", include("app_mailing.urls", namespace="app_mailing")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from users.views import (ActivateAccountView, AppUserListView, BlockUserView,
                         UnblockUserView, UserEmailConfirmationSentView,
                         UserLoginView, UserRegisterView, UserStartView)

app_name = "users"

urlpatterns = [
    path("start/", UserStartView.as_view(), name="start_page"),
    path("register/", UserRegisterView.as_view(), name="register_page"),
    path("activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate_account"),
    path("email-confirmation-sent/", UserEmailConfirmationSentView.as_view(), name="email_confirmation_sent_page"),
    path("login/", UserLoginView.as_view(), name="login_page"),
    path("logout/", LogoutView.as_view(), name="logout_page"),
    path("app-users/", AppUserListView.as_view(), name="user_list_page"),
    path("app-users/<int:pk>/block", BlockUserView.as_view(), name="block_user_page"),
    path("app-users/<int:pk>/unblock", UnblockUserView.as_view(), name="unblock_user_page"),
    # Часть для сброса пароля с использованием коробочного решения auth_views
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset/password_reset.html",
            # Django по умолчанию ищет коробочный шаблон в "registration/password_reset_email.html" и ожидает
            # стандартные имена URL-ов (password_reset_confirm и др.). Так как я изменил name= в urls.py
            # (сделал "name="password_reset_confirm_page""), то мне нужно использовать собственный шаблон письма
            # и указать свои url-имя в нём (email_template_name=).
            email_template_name="users/password_reset/email_confirm_reset.html",
            # Django по умолчанию в PasswordResetView ожидает, что путь для редиректа после успешной отправки email
            # будет называться коробочно вот так "password_reset_done", но я его изменил на "password_reset_done_page"
            # и поэтому необходимо это явно указать, чтоб не было ошибок.
            success_url=reverse_lazy("users:password_reset_done_page"),
        ),
        name="password_reset_page",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset/password_reset_done.html"
        ),
        name="password_reset_done_page",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset/password_reset_confirm.html",
            # Аналогично и для редиректа тут, чтобы после установки нового пароля была переадресация на
            # "users:password_reset_complete_page", а не на коробочное название, которое ожидает Django по умолчанию.
            success_url=reverse_lazy("users:password_reset_complete_page"),
        ),
        name="password_reset_confirm_page",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete_page",
    ),
]

app_mailing/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.cache import _generate_cache_key
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page

from app_mailing.forms import (AddNewMailingForm, AddNewMessageForm,
                               AddNewRecipientForm)
from app_mailing.models import Attempt, Mailing, Message, Recipient
from app_mailing.services import send_mailing, stop_mailing

# 1. Контроллеры для "Управление клиентами"


# Использую декоратор для создания кеша для всей страницы с параметром key_prefix, который потом нужен для
# сброса кэша страницы при добавлении/редактировании/удалении данных какого-либо объекта (получателя)
@method_decorator(cache_page(60 * 15, key_prefix="recipients_list"), name="dispatch")
class RecipientListView(LoginRequiredMixin, generic.ListView):
    """Представление для отображения списка Получателей рассылки."""

    model = Recipient
    template_name = "app_mailing/recipient/recipient_list.html"
    context_object_name = "recipients"

    def get_queryset(self):
        """1) Сортировка по ФИО (в алфавитном порядке).
        2) Ограничение данных по owner, т.е. выводим только те данные, где user==owner.
        3) Если пользователь входит в группу 'Менеджер сервиса', то выводим абсолютно все данные из БД."""
        qs = Recipient.objects.all()

        # Если у пользователя НЕТ системного разрешения на просмотр всех объектов - показываем только его объекты.
        if not self.request.user.groups.filter(name="Менеджер сервиса").exists():
            qs = qs.filter(owner=self.request.user).order_by("full_name")
        # Иначе показываем все.
        return qs.order_by("full_name")


class RecipientCreateView(LoginRequiredMixin, generic.CreateView):
    """Представление для добавления нового Получателя рассылки."""

    model = Recipient
    form_class = AddNewRecipientForm
    template_name = "app_mailing/recipient/recipient_add_update.html"
    success_url = reverse_lazy("app_mailing:recipient_list_page")

    def get_form_kwargs(self):
        """Метод для передачи в форму информации о текущем пользователе (владелец - owner), чтобы метод clean_email,
         который я добавил в самой форме (AddNewRecipientForm) мог корректно проверять уникальность email по владельцу.
         Без этого clean_email в форме (AddNewRecipientForm) не сможет определить, кому принадлежит объект."""
        kwargs = super().get_form_kwargs()
        kwargs["initial"] = {"owner": self.request.user}
        return kwargs

    def form_valid(self, form):
        """1) Отправка пользователю уведомления об успешном добавлении нового Получателя в список рассылки.
        2) Автоматическое заполнение текущим пользователем поля 'owner' при создании нового *Получателя рассылки*.
        3) Сброс кэша при добавлении нового Получателя."""
        messages.success(self.request, "Новый получатель успешно добавлен")

        form.instance.owner = self.request.user  # Привязываю текущего пользователя как owner

        # Формирую новый объект запроса с путём до списка всех получателей "recipient_list_page".
        # Сейчас выполняя запрос CreateView мы находимся внутри формы создания нового получателя
        # (например: /recipients/add/), а значит: self.request.path  ➝  "/mailing/recipients/add/".
        # Но, необходимо сбросить кэш списка всех получателей (именно в "/mailing/recipients/"), поэтому подменяю путь:
        # ШАГ 1: Здесь я запрашиваю у Django URL для именованного пути "app_mailing:recipient_list_page", что вернёт
        # нужную строку "/mailing/recipients/":
        list_path = reverse("app_mailing:recipient_list_page")
        # ШАГ 2: Здесь делаю так, чтоб Django временно сделал вид, что текущий запрос был к списку получателей.
        # Это нужно только на момент вызова _generate_cache_key() - чтобы он сгенерировал правильный ключ кэша
        # именно для страницы списка, а не формы редактирования:
        self.request.path = list_path
        # Далее задача: получить точное имя ключа кэша, по которому Django сохранил страницу "/mailing/recipients/",
        # то есть список получателей.
        # Django кэширует не просто по URL, а использует внутренний алгоритм для генерации ключа.
        # Вызываю внутреннюю Django-функцию _generate_cache_key(), которая создаёт имя кэша, которое Django использует
        # при сохранении страницы:
        cache_key = _generate_cache_key(
            # Передаю наш request - чтобы Django знал, какой путь учитывать при удалении кэша (в этом request.path уже
            # подменён выше!)
            request=self.request,
            # Кэш всегда создаётся для GET-запросов (POST и другие - нет)
            method="GET",
            # Если бы у меня были какие-то особые заголовки (Vary: Header), я бы указал их тут. Но нет ничего такого,
            # поэтому просто передаю пустой список
            headerlist=[],
            # Это префикс, который указывал в @cache_page(...) на RecipientListView. Очень важно, чтобы здесь было
            # точно то же самое. Иначе ключ не совпадёт - и кэш не удалится
            key_prefix="recipients_list"
        )
        cache.delete(cache_key)

        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, generic.UpdateView):
    """Представление для редактирования существующего Получателя рассылки."""

    model = Recipient
    form_class = AddNewRecipientForm
    template_name = "app_mailing/recipient/recipient_add_update.html"
    success_url = reverse_lazy("app_mailing:recipient_list_page")

    def dispatch(self, request, *args, **kwargs):
        """Метод выполняет проверку прав пользователя на редактирование *Получателя рассылки* (создатель получателя),
        заранее до выполнения любого запроса (GET, POST и т.д.)."""
        recipient = get_object_or_404(Recipient, pk=self.kwargs["pk"])
        if not request.user == recipient.owner:
            return HttpResponseForbidden(
                f"У вас нет прав для редактирования Получателя рассылки. Обратитесь к владельцу: {recipient.owner}"
            )
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """1) Отправка пользователю уведомления об успешном редактировании данных Получателя из списка рассылки.
        2) Сброс кэша при обновлении данных какого-либо Получателя из списка."""
        response = super().form_valid(form)

        # # ВАРИАНТ 1: через параметр самого объекта recipient с получением его через get_object():
        # recipient = self.get_object()
        # messages.success(self.request, f"Вы успешно обновили данные клиента: {recipient.email}")
        # ВАРИАНТ 2: обращаясь к параметру объекта через саму форму - form.instance.email:
        messages.success(self.request, f"Вы успешно обновили данные клиента: {form.instance.email}")

        # Формирую новый объект запроса с путём до списка всех получателей "recipient_list_page".
        # Сейчас выполняя запрос UpdateView мы находимся внутри формы редактирования какого-то одного получателя
        # (например: /mailing/recipients/24/update/), а значит: self.request.path  ➝  "/mailing/recipients/24/update/".
        # Но, необходимо сбросить кэш списка всех получателей (именно в "/mailing/recipients/"), поэтому подменяю путь:
        # ШАГ 1: Здесь я запрашиваю у Django URL для именованного пути "app_mailing:recipient_list_page", что вернёт
        # нужную строку "/mailing/recipients/":
        list_path = reverse("app_mailing:recipient_list_page")
        # ШАГ 2: Здесь делаю так, чтоб Django временно сделал вид, что текущий запрос был к списку получателей.
        # Это нужно только на момент вызова _generate_cache_key() - чтобы он сгенерировал правильный ключ кэша
        # именно для страницы списка, а не формы редактирования:
        self.request.path = list_path
        # Далее задача: получить точное имя ключа кэша, по которому Django сохранил страницу "/mailing/recipients/",
        # то есть список получателей.
        # Django кэширует не просто по URL, а использует внутренний алгоритм для генерации ключа.
        # Вызываю внутреннюю Django-функцию _generate_cache_key(), которая создаёт имя кэша, которое Django использует
        # при сохранении страницы:
        cache_key = _generate_cache_key(
            # Передаю наш request - чтобы Django знал, какой путь учитывать при удалении кэша (в этом request.path уже
            # подменён выше!)
            request=self.request,
            # Кэш всегда создаётся для GET-запросов (POST и другие - нет)
            method="GET",
            # Если бы у меня были какие-то особые заголовки (Vary: Header), я бы указал их тут. Но нет ничего такого,
            # поэтому просто передаю пустой список
            headerlist=[],
            # Это префикс, который указывал в @cache_page(...) на RecipientListView. Очень важно, чтобы здесь было
            # точно то же самое. Иначе ключ не совпадёт - и кэш не удалится
            key_prefix="recipients_list"
        )
        cache.delete(cache_key)

        return response


class RecipientDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Представление для удаления Получателя рассылки."""

    model = Recipient
    template_name = "app_mailing/recipient/recipient_delete.html"
    context_object_name = "recipient"
    success_url = reverse_lazy("app_mailing:recipient_list_page")

    def dispatch(self, request, *args, **kwargs):
        """Метод выполняет проверку прав пользователя на удаление *Получателя рассылки* (создатель получателя),
        заранее до выполнения любого запроса (GET, POST и т.д.)."""

app_mailing/templates/app_mailing/mailing/mailing_add_update.html
{% extends 'app_mailing/base.html' %}

{% block title %}Добавление рассылки{% endblock %}

{% block content %}

<!-- Заголовок страницы -->
<div class="text-center my-5">
    <h2 class="fw-bold">Добавьте новую рассылку</h2>
    <p class="text-muted">Управляйте вашими email-рассылками</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card-body mt-4">

                <!-- Отображение формы AddNewMailingForm(forms.ModelForm) для добавления/обновления рассылки-->
                <form method="post" enctype="multipart/form-data" class="form-floating">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <!-- Кнопки -->
                    <div class="text-center">
                        <button type="submit" class="btn btn-success mt-4 me-2">Сохранить</button>
                        <a href="{% url 'app_mailing:mailing_list_page' %}" class="btn btn-outline-primary mt-4">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_mailing/templates/app_mailing/mailing/mailing_delete.html
{% extends 'app_mailing/base.html' %}

{% block title %}Удаление рассылки{% endblock %}

{% block content %}

<!-- Заголовок страницы -->
<div class="text-center my-5">
    <h2 class="fw-bold">Подтверждение удаления рассылки:</h2>
    <table class="table table-hover align-middle table-bordered shadow-sm">
        <tbody>
        <tr>
            <!-- Статус -->
            <td class="text-center">
                {% if mailing.status == "launched" %}
                <span class="text-success fw-bold">{{ mailing.get_status_display }}</span>
                {% elif mailing.status == "accomplished" %}
                <span class="text-secondary fw-bold">{{ mailing.get_status_display }}</span>
                {% elif mailing.status == "created" %}
                <span class="fw-bold">{{ mailing.get_status_display }}</span>
                {% else %}
                {{ mailing.get_status_display }}
                {% endif %}
            </td>
            <!-- Сообщение -->
            <td>{{ mailing.message.message_subject }}</td>
            <!-- Получатели -->
            <td>
                <ul class="mb-0 ps-3" style="min-width: 350px;">
                    {% for recipient in mailing.recipients.all %}
                    <li>{{ recipient.full_name }}</li>
                    {% empty %}
                    <li class="text-muted">Нет получателей</li>
                    {% endfor %}
                </ul>
            </td>
<!--            <td>{{ mailing.recipients }}</td>-->
        </tr>
        </tbody>
    </table>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card-body mt-4">
                <h4>Вы действительно хотите удалить эту рассылку?</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <!-- Кнопки -->
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger mt-4 me-2">Удалить</button>
                        <a href="{% url 'app_mailing:mailing_list_page' %}"
                           class="btn btn-outline-primary mt-4">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_mailing/templates/app_mailing/mailing/mailing_list.html
{% extends 'app_mailing/base.html' %}

{% block title %}Рассылки{% endblock %}

{% block content %}

<!--Чтобы корректно работал фильтр "now" в модальном окне при планировании запуска рассылки нужно добавить:-->
{% load tz %}
{% load l10n %}


<!-- Заголовок страницы -->
<div class="text-center my-5">
    <h2 class="fw-bold">Список рассылок</h2>
    <p class="text-muted">Управляйте вашими email-рассылками</p>
</div>

<!-- Кнопка добавления -->
<div class="d-flex justify-content-end mb-4">
    {% if not user.is_blocked %}
    <a href="{% url 'app_mailing:mailing_add_page' %}" class="btn btn-success shadow-sm">
        <i class="fas fa-plus me-2"></i>Добавить рассылку
    </a>
    {% else %}
    <div class="alert alert-danger text-center mt-3">
        Вы заблокированы. Обратитесь к менеджеру: +1 342 932 2345
    </div>
    {% endif %}
</div>

<!-- Таблица -->
<div class="table-responsive">
    <table class="table table-hover align-middle table-bordered shadow-sm">

        <!-- Оглавление таблицы -->
        <thead class="table-dark text-center align-middle">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Первая отправка</th>
            <th scope="col">Окончание отправки</th>
            <th scope="col">Статус рассылки</th>
            <th scope="col">Сообщение рассылки</th>
            <th scope="col">Получатели рассылки</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>

        <!-- Содержимое таблицы -->
        <tbody>
        {% for mailing in mailings %}
        <tr class="{% if user != mailing.owner %}table-secondary{% endif %}">

            <!-- Нумерация, дата запуска, дата окончания -->
            <th class="text-center" scope="row">{{ forloop.counter }}</th>
            <td class="text-center" style="min-width: 180px;">{{ mailing.first_message_sending|date:"d.m.Y, H:i"|default:"—" }}
            </td>
            <td class="text-center" style="min-width: 180px;">{{ mailing.end_message_sending|date:"d.m.Y,H:i"|default:"—" }}
            </td>

            <!-- Статус рассылки -->
            <td class="text-center">
                {% if mailing.status == "launched" %}
                <span class="text-success fw-bold">{{ mailing.get_status_display }}</span>

                {% elif mailing.status == "accomplished" %}
                <span class="text-secondary fw-bold">{{ mailing.get_status_display }}</span>

                {% elif mailing.status == "created" %}
                <span class="fw-bold">{{ mailing.get_status_display }}</span>

                <!-- Кнопка ЗАПУСТИТЬ для статуса СОЗДАНА -->
                {% if user == mailing.owner %}
                <div>
                    <form method="post" action="{% url 'app_mailing:start_mailing_page' mailing.pk %}" class="d-inline">
                        {% csrf_token %}
                        <!-- Если рассылка уже запланирована, то нет тут кнопок и показываем планируемую дату и время -->
                        {% if mailing.first_message_sending %}
                        <div class="text-muted small fst-italic">
                            Запланировано на: {{ mailing.first_message_sending|date:"d.m.Y, H:i" }}
                        </div>
                        <!-- Если рассылка еще не запланирована отображаем такие кнопки действий -->
                        {% else %}
                            {% if not user.is_blocked %}
                            <!-- Кнопка для немедленного запуска-->
                            <button type="submit" class="btn btn-sm btn-success me-1">
                                <i class="fas fa-play"></i> Запустить
                            </button>
                            <!-- Кнопка для открытия модального окна планирования запуска-->
                            <!-- Важно: data-bs-target="#scheduleModal-{{ mailing.pk }}" — уникальный ID для каждого модального окна по рассылке.-->
                            <button type="button" class="btn btn-sm btn-outline-primary me-1" data-bs-toggle="modal" data-bs-target="#scheduleModal-{{ mailing.pk }}">
                                <i class="fas fa-clock"></i> Запланировать
                            </button>
                            {% else %}
                            <button type="submit" class="btn btn-sm btn-success me-1 disabled">
                                <i class="fas fa-play"></i> Запустить
                            </button>
                            <button type="button" class="btn btn-sm btn-outline-primary me-1 disabled">
                                <i class="fas fa-clock"></i> Запланировать
                            </button>
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
                {% else %}
                <div class="text-muted small fst-italic mt-1">
                    (запустить может только создатель рассылки)
                </div>
                {% endif %}

                <!-- Настройка вида модального окна для планирования запуска рассылки -->
                <div class="modal fade" id="scheduleModal-{{ mailing.pk }}" tabindex="-1"
                     aria-labelledby="scheduleModalLabel-{{ mailing.pk }}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <!-- Заголовок модального окна-->
                            <div class="modal-header">
                                <h5 class="modal-title" id="scheduleModalLabel-{{ mailing.pk }}">
                                    Запланировать рассылку
                                </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                            </div>
                            <!-- Форма модального окна
                            ВАЖНО! "min="{{ now|date:'Y-m-d\TH:i' }}"" не будет работать без добавления определения текущей даты в контроллере. Сам браузер это не делает-->
                            <form method="post" action="{% url 'app_mailing:schedule_mailing_page' mailing.pk %}">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div class="mb-3">
                                        <label for="datetime-{{ mailing.pk }}" class="form-label">Дата и время запуска</label>
                                        <input
                                                type="datetime-local"
                                                id="datetime-{{ mailing.pk }}"
                                                name="first_message_sending"
                                                class="form-control"
                                                required
                                                min="{{ now|date:'Y-m-d\TH:i' }}"
                                        >
                                    </div>
                                </div>
                                <!-- Кнопки модального окна-->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                        Отмена
                                    </button>
                                    <button type="submit" class="btn btn-primary">
                                        Сохранить
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                {% else %}
                {{ mailing.get_status_display }}

                {% endif %}
            </td>

            <!-- Сообщение рассылки-->
            <td>{{ mailing.message.message_subject|default:"—" }}</td>

            <!-- Получатели -->
            <!-- ВАРИАНТ 1: Отображать список получателей с помощью popover, чтоб для Получателей отображалось -->
            <!-- "количество" и "тултип с ФИО" (при наведении отображаю ФИО получателей) -->
            <td class="text-center">
                <span
                        data-bs-toggle="popover"
                        data-bs-html="true"
                        data-bs-trigger="focus"
                        title="Получатели:"
                        data-bs-content="{% for r in mailing.recipients.all %}{{ r.full_name }}<br>{% endfor %}"
                        tabindex="0"
                        class="btn btn-sm btn-outline-dark"
                >{{ mailing.recipients.count }}</span>
            </td>
            <!--            &lt;!&ndash; ВАРИАНТ 2: Отображать список получателей с помощью tooltip, чтоб для Получателей отображалось &ndash;&gt;-->
            <!--            &lt;!&ndash; "количество" и "тултип с ФИО" (при наведении отображаю ФИО получателей) &ndash;&gt;-->
            <!--            <td class="text-center">-->
            <!--                {% with recipients=mailing.recipients.all %}-->
            <!--                {% if recipients.count <= 0 %}-->
            <!--                <span-->
            <!--                        data-bs-toggle="tooltip"-->
            <!--                        data-bs-placement="top"-->
            <!--                        data-bs-html="true"-->
            <!--                        title="{% for r in recipients %}{{ r.full_name }}<br>{% endfor %}"-->
            <!--                >{{ recipients.count }}-->
            <!--                </span>-->
            <!--                {% else %}-->
            <!--                <a href="{% url 'app_mailing:mailing_update_page' mailing.pk %}">{{ recipients.count }}</a>-->
            <!--                {% endif %}-->
            <!--                {% endwith %}-->
            <!--            </td>-->

            <!-- Кнопки действия -->
            {% if user == mailing.owner or perms.users.can_block_user %}
            <td class="text-center">
                {% if mailing.status == "launched" %}
                <form method="post" action="{% url 'app_mailing:stop_mailing_page' mailing.pk %}" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-secondary" title="Отменить рассылку">
                        <i class="fas fa-stop"></i>
                    </button>
                </form>
                {% elif mailing.status == "created" and user == mailing.owner %}


                    {% if mailing.first_message_sending %}
                    <form method="post" action="{% url 'app_mailing:stop_mailing_page' mailing.pk %}" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-secondary" title="Отменить рассылку">
                            <i class="fas fa-stop"></i>
                        </button>
                    </form>


                    {% else %}
                        {% if not user.is_blocked %}
                        <a href="{% url 'app_mailing:mailing_update_page' mailing.pk %}" class="btn btn-sm btn-warning me-1" title="Редактировать рассылку">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="{% url 'app_mailing:mailing_delete_page' mailing.pk %}" class="btn btn-sm btn-danger me-1" title="Удалить рассылку">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        {% else %}
                        <a href="#" class="btn btn-sm btn-warning me-1 disabled">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" class="btn btn-sm btn-danger me-1 disabled">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        {% endif %}
                    {% endif %}
                {% else %}
                <span class="text-muted">
                        —
                    </span>
                {% endif %}
            </td>
            {% else %}
            <td class="text-center text-muted">—</td>
            {% endif %}

        </tr>

        {% empty %}
        <tr>
            <td colspan="5" class="text-center text-muted py-4">Пока нет рассылок</td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}